--------------------------------------------------------------------------------
--
--  FUNCTION "ISTRUE" DEFINED FOR 8 ARGUMENTS DOWN TO 0 ARGUMENTS
--
--------------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION TRUTHOBJ/ISTRUE (
  CONDNAME CHAR(15) ,
  BANKCODE CHAR(4) ,
  DEBTTYPE CHAR(4) ,
  STATE CHAR(2) ,
  AREACODE DECIMAL(3, 0) ,
  EXCHANGE DECIMAL(3, 0) ,
  GENDER CHAR(1) ,
  MARITAL CHAR(1) ,
  AGE DECIMAL(3, 0) )
  RETURNS CHAR(1)
  LANGUAGE RPGLE
  SPECIFIC TRUTHOBJ/ISTRUE8
  NOT DETERMINISTIC
  READS SQL DATA
  CALLED ON NULL INPUT
  NOT FENCED
  EXTERNAL NAME 'TRUTHOBJ/TRUTHTOOL(ISTRUE)'
  PARAMETER STYLE GENERAL ;

COMMENT ON PARAMETER SPECIFIC FUNCTION TRUTHOBJ/ISTRUE8
( CONDNAME IS 'Condition Name' ,
  BANKCODE IS 'Bank Code' ,
  DEBTTYPE IS 'Debt Type' ,
  STATE IS 'State Abbreviation' ,
  AREACODE IS 'Phone Area Code' ,
  EXCHANGE IS 'Phone Exchange' ,
  GENDER IS 'Gender Code' ,
  MARITAL IS 'Marital Status' ,
  AGE IS 'Attained Age' ) ;

LABEL ON SPECIFIC FUNCTION TRUTHOBJ/ISTRUE8
  IS 'Is Condition True (8 Arguments)' ;

--------------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION TRUTHOBJ/ISTRUE (
  CONDNAME CHAR(15) ,
  BANKCODE CHAR(4) ,
  DEBTTYPE CHAR(4) ,
  STATE CHAR(2) ,
  AREACODE DECIMAL(3, 0) ,
  EXCHANGE DECIMAL(3, 0) ,
  GENDER CHAR(1) ,
  MARITAL CHAR(1) )
  RETURNS CHAR(1)
  LANGUAGE RPGLE
  SPECIFIC TRUTHOBJ/ISTRUE7
  NOT DETERMINISTIC
  READS SQL DATA
  CALLED ON NULL INPUT
  NOT FENCED
  EXTERNAL NAME 'TRUTHOBJ/TRUTHTOOL(ISTRUE)'
  PARAMETER STYLE GENERAL ;

COMMENT ON PARAMETER SPECIFIC FUNCTION TRUTHOBJ/ISTRUE7
( CONDNAME IS 'Condition Name' ,
  BANKCODE IS 'Bank Code' ,
  DEBTTYPE IS 'Debt Type' ,
  STATE IS 'State Abbreviation' ,
  AREACODE IS 'Phone Area Code' ,
  EXCHANGE IS 'Phone Exchange' ,
  GENDER IS 'Gender Code' ,
  MARITAL IS 'Marital Status' ) ;

LABEL ON SPECIFIC FUNCTION TRUTHOBJ/ISTRUE7
  IS 'Is Condition True (7 Arguments)' ;

--------------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION TRUTHOBJ/ISTRUE (
  CONDNAME CHAR(15) ,
  BANKCODE CHAR(4) ,
  DEBTTYPE CHAR(4) ,
  STATE CHAR(2) ,
  AREACODE DECIMAL(3, 0) ,
  EXCHANGE DECIMAL(3, 0) ,
  GENDER CHAR(1) )
  RETURNS CHAR(1)
  LANGUAGE RPGLE
  SPECIFIC TRUTHOBJ/ISTRUE6
  NOT DETERMINISTIC
  READS SQL DATA
  CALLED ON NULL INPUT
  NOT FENCED
  EXTERNAL NAME 'TRUTHOBJ/TRUTHTOOL(ISTRUE)'
  PARAMETER STYLE GENERAL ;

COMMENT ON PARAMETER SPECIFIC FUNCTION TRUTHOBJ/ISTRUE6
( CONDNAME IS 'Condition Name' ,
  BANKCODE IS 'Bank Code' ,
  DEBTTYPE IS 'Debt Type' ,
  STATE IS 'State Abbreviation' ,
  AREACODE IS 'Phone Area Code' ,
  EXCHANGE IS 'Phone Exchange' ,
  GENDER IS 'Gender Code' ) ;

LABEL ON SPECIFIC FUNCTION TRUTHOBJ/ISTRUE6
  IS 'Is Condition True (6 Arguments)' ;

--------------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION TRUTHOBJ/ISTRUE (
  CONDNAME CHAR(15) ,
  BANKCODE CHAR(4) ,
  DEBTTYPE CHAR(4) ,
  STATE CHAR(2) ,
  AREACODE DECIMAL(3, 0) ,
  EXCHANGE DECIMAL(3, 0) )
  RETURNS CHAR(1)
  LANGUAGE RPGLE
  SPECIFIC TRUTHOBJ/ISTRUE5
  NOT DETERMINISTIC
  READS SQL DATA
  CALLED ON NULL INPUT
  NOT FENCED
  EXTERNAL NAME 'TRUTHOBJ/TRUTHTOOL(ISTRUE)'
  PARAMETER STYLE GENERAL ;

COMMENT ON PARAMETER SPECIFIC FUNCTION TRUTHOBJ/ISTRUE5
( CONDNAME IS 'Condition Name' ,
  BANKCODE IS 'Bank Code' ,
  DEBTTYPE IS 'Debt Type' ,
  STATE IS 'State Abbreviation' ,
  AREACODE IS 'Phone Area Code' ,
  EXCHANGE IS 'Phone Exchange' ) ;

LABEL ON SPECIFIC FUNCTION TRUTHOBJ/ISTRUE5
  IS 'Is Condition True (5 Arguments)' ;

--------------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION TRUTHOBJ/ISTRUE (
  CONDNAME CHAR(15) ,
  BANKCODE CHAR(4) ,
  DEBTTYPE CHAR(4) ,
  STATE CHAR(2) ,
  AREACODE DECIMAL(3, 0) )
  RETURNS CHAR(1)
  LANGUAGE RPGLE
  SPECIFIC TRUTHOBJ/ISTRUE4
  NOT DETERMINISTIC
  READS SQL DATA
  CALLED ON NULL INPUT
  NOT FENCED
  EXTERNAL NAME 'TRUTHOBJ/TRUTHTOOL(ISTRUE)'
  PARAMETER STYLE GENERAL ;

COMMENT ON PARAMETER SPECIFIC FUNCTION TRUTHOBJ/ISTRUE4
( CONDNAME IS 'Condition Name' ,
  BANKCODE IS 'Bank Code' ,
  DEBTTYPE IS 'Debt Type' ,
  STATE IS 'State Abbreviation' ,
  AREACODE IS 'Phone Area Code' ) ;

LABEL ON SPECIFIC FUNCTION TRUTHOBJ/ISTRUE4
  IS 'Is Condition True (4 Arguments)' ;

--------------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION TRUTHOBJ/ISTRUE (
  CONDNAME CHAR(15) ,
  BANKCODE CHAR(4) ,
  DEBTTYPE CHAR(4) ,
  STATE CHAR(2) )
  RETURNS CHAR(1)
  LANGUAGE RPGLE
  SPECIFIC TRUTHOBJ/ISTRUE3
  NOT DETERMINISTIC
  READS SQL DATA
  CALLED ON NULL INPUT
  NOT FENCED
  EXTERNAL NAME 'TRUTHOBJ/TRUTHTOOL(ISTRUE)'
  PARAMETER STYLE GENERAL ;

COMMENT ON PARAMETER SPECIFIC FUNCTION TRUTHOBJ/ISTRUE3
( CONDNAME IS 'Condition Name' ,
  BANKCODE IS 'Bank Code' ,
  DEBTTYPE IS 'Debt Type' ,
  STATE IS 'State Abbreviation' ) ;

LABEL ON SPECIFIC FUNCTION TRUTHOBJ/ISTRUE3
  IS 'Is Condition True (3 Arguments)' ;

--------------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION TRUTHOBJ/ISTRUE (
  CONDNAME CHAR(15) ,
  BANKCODE CHAR(4) ,
  DEBTTYPE CHAR(4) )
  RETURNS CHAR(1)
  LANGUAGE RPGLE
  SPECIFIC TRUTHOBJ/ISTRUE2
  NOT DETERMINISTIC
  READS SQL DATA
  CALLED ON NULL INPUT
  NOT FENCED
  EXTERNAL NAME 'TRUTHOBJ/TRUTHTOOL(ISTRUE)'
  PARAMETER STYLE GENERAL ;

COMMENT ON PARAMETER SPECIFIC FUNCTION TRUTHOBJ/ISTRUE2
( CONDNAME IS 'Condition Name' ,
  BANKCODE IS 'Bank Code' ,
  DEBTTYPE IS 'Debt Type' ) ;

LABEL ON SPECIFIC FUNCTION TRUTHOBJ/ISTRUE2
  IS 'Is Condition True (2 Arguments)' ;

--------------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION TRUTHOBJ/ISTRUE (
  CONDNAME CHAR(15) ,
  BANKCODE CHAR(4) )
  RETURNS CHAR(1)
  LANGUAGE RPGLE
  SPECIFIC TRUTHOBJ/ISTRUE1
  NOT DETERMINISTIC
  READS SQL DATA
  CALLED ON NULL INPUT
  NOT FENCED
  EXTERNAL NAME 'TRUTHOBJ/TRUTHTOOL(ISTRUE)'
  PARAMETER STYLE GENERAL ;

COMMENT ON PARAMETER SPECIFIC FUNCTION TRUTHOBJ/ISTRUE1
( CONDNAME IS 'Condition Name' ,
  BANKCODE IS 'Bank Code' ) ;

LABEL ON SPECIFIC FUNCTION TRUTHOBJ/ISTRUE1
  IS 'Is Condition True (1 Argument)' ;

--------------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION TRUTHOBJ/ISTRUE (
  CONDNAME CHAR(15) )
  RETURNS CHAR(1)
  LANGUAGE RPGLE
  SPECIFIC TRUTHOBJ/ISTRUE0
  NOT DETERMINISTIC
  READS SQL DATA
  CALLED ON NULL INPUT
  NOT FENCED
  EXTERNAL NAME 'TRUTHOBJ/TRUTHTOOL(ISTRUE)'
  PARAMETER STYLE GENERAL ;

COMMENT ON PARAMETER SPECIFIC FUNCTION TRUTHOBJ/ISTRUE0
( CONDNAME IS 'Condition Name' ) ;

LABEL ON SPECIFIC FUNCTION TRUTHOBJ/ISTRUE0
  IS 'Is Condition True (0 Arguments)' ;

--------------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION TRUTHOBJ/CALLEDFROMPGM (
  PROGNAME CHAR(10) )
  RETURNS CHAR(1)
  LANGUAGE RPGLE
  SPECIFIC TRUTHOBJ/CALLEDFROMPGM
  NOT DETERMINISTIC
  READS SQL DATA
  CALLED ON NULL INPUT
  NOT FENCED
  EXTERNAL NAME 'TRUTHOBJ/TRUTHTOOL(CALLEDFROMPGM)'
  PARAMETER STYLE GENERAL ;

COMMENT ON PARAMETER SPECIFIC FUNCTION TRUTHOBJ/CALLEDFROMPGM
( PROGNAME IS 'Application Program Name' ) ;

LABEL ON SPECIFIC FUNCTION TRUTHOBJ/CALLEDFROMPGM
  IS 'Called From Application Program' ;

