--------------------------------------------------------------------------------
--
--  BUILD SCHEMA FOR TRUTH MATRIX.
--    INCLUDES TEMPORAL TABLES FOR MATRIX HEADER AND DETAIL, PLUS HISTORY.
--    VERSIONS FOR EACH.  ALSO INCLUDES SIMPLE INDEXES.
--
--------------------------------------------------------------------------------

CREATE SCHEMA TRUTHDTA;

--------------------------------------------------------------------------------

CREATE TABLE TRUTHDTA/MTRXHEADH (
  HEADERID INTEGER NOT NULL ,
  CONDNAME CHAR(15) CCSID 37 NOT NULL ,
  ENABLED CHAR(1) CCSID 37 NOT NULL ,
  EFFECTIVE DATE NOT NULL DEFAULT '0001-01-01' ,
  EXPIRATION DATE NOT NULL DEFAULT '9999-12-31' ,
  DESCRIP VARCHAR(50) CCSID 37 NOT NULL ,
  "PROGRAM" CHAR(10) CCSID 37 NOT NULL DEFAULT '' ,
  "USERID" CHAR(18) CCSID 37 NOT NULL DEFAULT USER ,
  SYS_START TIMESTAMP(12) NOT NULL ,
  SYS_END TIMESTAMP(12) NOT NULL ,
  TS_ID TIMESTAMP(12) NOT NULL )

  RCDFMT MTRXHEADH  ;

LABEL ON TABLE TRUTHDTA/MTRXHEADH
  IS 'Truth Matrix Header History' ;

LABEL ON COLUMN TRUTHDTA/MTRXHEADH
( HEADERID IS 'Header              Unique ID' ,
  CONDNAME IS 'Condition           Nickname' ,
  ENABLED IS 'Enabled             (Y/N)' ,
  EFFECTIVE IS 'Effective           Date' ,
  EXPIRATION IS 'Expiration          Date' ,
  DESCRIP IS 'Description          ' ,
  "PROGRAM" IS 'Eligible            Program' ) ;

LABEL ON COLUMN TRUTHDTA/MTRXHEADH
( HEADERID TEXT IS 'Header Unique ID' ,
  CONDNAME TEXT IS 'Condition Nickname' ,
  ENABLED TEXT IS 'Enabled (Y/N)' ,
  EFFECTIVE TEXT IS 'Effective Date' ,
  EXPIRATION TEXT IS 'Expiration Date' ,
  DESCRIP TEXT IS 'Description' ,
  "PROGRAM" TEXT IS 'Eligible Program' ) ;


CREATE TABLE TRUTHDTA/MTRXDETLH (
  HEADERID INTEGER NOT NULL ,
  DETAILID INTEGER NOT NULL ,
  ENABLED CHAR(1) CCSID 37 NOT NULL DEFAULT 'Y' ,
  EFFECTIVE DATE NOT NULL DEFAULT '0001-01-01' ,
  EXPIRATION DATE NOT NULL DEFAULT '9999-12-31' ,
  BANKCODE CHAR(4) CCSID 37 NOT NULL DEFAULT '' ,
  DEBTTYPE CHAR(4) CCSID 37 NOT NULL DEFAULT '' ,
  STATE CHAR(2) CCSID 37 NOT NULL DEFAULT '' ,
  AREACODE DECIMAL(3, 0) NOT NULL DEFAULT 0 ,
  EXCHANGE DECIMAL(3, 0) NOT NULL DEFAULT 0 ,
  GENDER CHAR(1) CCSID 37 NOT NULL DEFAULT '' ,
  MARITAL CHAR(1) CCSID 37 NOT NULL DEFAULT '' ,
  AGEFROM DECIMAL(3, 0) NOT NULL DEFAULT 0 ,
  AGETHRU DECIMAL(3, 0) NOT NULL DEFAULT 0 ,
  "PROGRAM" CHAR(10) CCSID 37 NOT NULL DEFAULT '' ,
  "USERID" CHAR(18) CCSID 37 NOT NULL DEFAULT USER ,
  SYS_START TIMESTAMP(12) NOT NULL ,
  SYS_END TIMESTAMP(12) NOT NULL ,
  TS_ID TIMESTAMP(12) NOT NULL )

  RCDFMT MTRXDETLH  ;

LABEL ON TABLE TRUTHDTA/MTRXDETLH
  IS 'Truth Matrix Detail History' ;

LABEL ON COLUMN TRUTHDTA/MTRXDETLH
( HEADERID IS 'Header              Unique ID' ,
  DETAILID IS 'Detail              Unique ID' ,
  ENABLED IS 'Enabled             (Y/N)' ,
  EFFECTIVE IS 'Effective           Date' ,
  EXPIRATION IS 'Expiration          Date' ,
  BANKCODE IS 'Bank                Code' ,
  DEBTTYPE IS 'Debt                Type                Code' ,
  STATE IS 'State               Code' ,
  AREACODE IS 'Telephone           Area Code' ,
  EXCHANGE IS 'Telephone           Exchange' ,
  GENDER IS 'Gender              Code' ,
  MARITAL IS 'Marital             Status' ,
  AGEFROM IS 'Age                 Range               From' ,
  AGETHRU IS 'Age                 Range               Thru' ,
  "PROGRAM" IS 'Eligible            Program' ) ;

LABEL ON COLUMN TRUTHDTA/MTRXDETLH
( HEADERID TEXT IS 'Header Unique ID' ,
  DETAILID TEXT IS 'Detail Unique ID' ,
  ENABLED TEXT IS 'Enabled (Y/N)' ,
  EFFECTIVE TEXT IS 'Effective Date' ,
  EXPIRATION TEXT IS 'Expiration Date' ,
  BANKCODE TEXT IS 'Bank Code' ,
  DEBTTYPE TEXT IS 'Debt Type Code' ,
  STATE TEXT IS 'State Code' ,
  AREACODE TEXT IS 'Telephone Area Code' ,
  EXCHANGE TEXT IS 'Telephone Exchange' ,
  GENDER TEXT IS 'Gender Code' ,
  MARITAL TEXT IS 'Marital Status' ,
  AGEFROM TEXT IS 'Age Range From' ,
  AGETHRU TEXT IS 'Age Range Thru' ,
  "PROGRAM" TEXT IS 'Eligible Program' ) ;


CREATE TABLE TRUTHDTA/MTRXHEAD (
  HEADERID INTEGER GENERATED ALWAYS AS IDENTITY (
  START WITH 1 INCREMENT BY 1
  NO MINVALUE NO MAXVALUE
  NO CYCLE NO ORDER
  NO CACHE )
  ,
  CONDNAME CHAR(15) CCSID 37 NOT NULL DEFAULT '' ,
  ENABLED CHAR(1) CCSID 37 NOT NULL DEFAULT '' ,
  EFFECTIVE DATE NOT NULL DEFAULT '0001-01-01' ,
  EXPIRATION DATE NOT NULL DEFAULT '9999-12-31' ,
  DESCRIP VARCHAR(50) CCSID 37 NOT NULL DEFAULT '' ,
  "PROGRAM" CHAR(10) CCSID 37 NOT NULL DEFAULT '' ,
  "USERID" CHAR(18) CCSID 37 NOT NULL DEFAULT USER ,
  SYS_START TIMESTAMP(12) GENERATED ALWAYS AS ROW BEGIN NOT NULL ,
  SYS_END TIMESTAMP(12) GENERATED ALWAYS AS ROW END NOT NULL ,
  TS_ID TIMESTAMP(12) GENERATED ALWAYS AS TRANSACTION START ID NOT NULL ,
  CONSTRAINT TRUTHDTA/Q_TRUTH_MTRXHEAD_HEADERID_00001 PRIMARY KEY( HEADERID ) ,
  PERIOD SYSTEM_TIME ( SYS_START , SYS_END ) )

  RCDFMT MTRXHEAD   ;

LABEL ON TABLE TRUTHDTA/MTRXHEAD
  IS 'Truth Matrix Header' ;

LABEL ON COLUMN TRUTHDTA/MTRXHEAD
( HEADERID IS 'Header              Unique ID' ,
  CONDNAME IS 'Condition           Nickname' ,
  ENABLED IS 'Enabled             (Y/N)' ,
  EFFECTIVE IS 'Effective           Date' ,
  EXPIRATION IS 'Expiration          Date' ,
  DESCRIP IS 'Description          ' ,
  "PROGRAM" IS 'Eligible            Program' ) ;

LABEL ON COLUMN TRUTHDTA/MTRXHEAD
( HEADERID TEXT IS 'Header Unique ID' ,
  CONDNAME TEXT IS 'Condition Nickname' ,
  ENABLED TEXT IS 'Enabled (Y/N)' ,
  EFFECTIVE TEXT IS 'Effective Date' ,
  EXPIRATION TEXT IS 'Expiration Date' ,
  DESCRIP TEXT IS 'Description' ,
  "PROGRAM" TEXT IS 'Eligible Program' ) ;

ALTER TABLE TRUTHDTA/MTRXHEAD
  ADD VERSIONING USE HISTORY TABLE TRUTHDTA/MTRXHEADH ;


CREATE TABLE TRUTHDTA/MTRXDETL (
  HEADERID INTEGER NOT NULL ,
  DETAILID INTEGER GENERATED ALWAYS AS IDENTITY (
  START WITH 1 INCREMENT BY 1
  NO MINVALUE NO MAXVALUE
  NO CYCLE NO ORDER
  NO CACHE )
  ,
  ENABLED CHAR(1) CCSID 37 NOT NULL DEFAULT 'Y' ,
  EFFECTIVE DATE NOT NULL DEFAULT '0001-01-01' ,
  EXPIRATION DATE NOT NULL DEFAULT '9999-12-31' ,
  BANKCODE CHAR(4) CCSID 37 NOT NULL DEFAULT '' ,
  DEBTTYPE CHAR(4) CCSID 37 NOT NULL DEFAULT '' ,
  STATE CHAR(2) CCSID 37 NOT NULL DEFAULT '' ,
  AREACODE DECIMAL(3, 0) NOT NULL DEFAULT 0 ,
  EXCHANGE DECIMAL(3, 0) NOT NULL DEFAULT 0 ,
  GENDER CHAR(1) CCSID 37 NOT NULL DEFAULT '' ,
  MARITAL CHAR(1) CCSID 37 NOT NULL DEFAULT '' ,
  AGEFROM DECIMAL(3, 0) NOT NULL DEFAULT 0 ,
  AGETHRU DECIMAL(3, 0) NOT NULL DEFAULT 0 ,
  "PROGRAM" CHAR(10) CCSID 37 NOT NULL DEFAULT '' ,
  "USERID" CHAR(18) CCSID 37 NOT NULL DEFAULT USER ,
  SYS_START TIMESTAMP(12) GENERATED ALWAYS AS ROW BEGIN NOT NULL ,
  SYS_END TIMESTAMP(12) GENERATED ALWAYS AS ROW END NOT NULL ,
  TS_ID TIMESTAMP(12) GENERATED ALWAYS AS TRANSACTION START ID NOT NULL ,
  CONSTRAINT TRUTHDTA/Q_TRUTH_MTRXDETL_DETAILID_00001 PRIMARY KEY( DETAILID ) ,
  PERIOD SYSTEM_TIME ( SYS_START , SYS_END ) )

  RCDFMT MTRXDETL   ;

ALTER TABLE TRUTHDTA/MTRXDETL
  ADD CONSTRAINT TRUTHDTA/Q_TRUTH_MTRXDETL_HEADERID_00001
  FOREIGN KEY( HEADERID )
  REFERENCES TRUTHDTA/MTRXHEAD ( HEADERID )
  ON DELETE RESTRICT
  ON UPDATE NO ACTION ;

LABEL ON TABLE TRUTHDTA/MTRXDETL
  IS 'Truth Matrix Detail' ;

LABEL ON COLUMN TRUTHDTA/MTRXDETL
( HEADERID IS 'Header              Unique ID' ,
  DETAILID IS 'Detail              Unique ID' ,
  ENABLED IS 'Enabled             (Y/N)' ,
  EFFECTIVE IS 'Effective           Date' ,
  EXPIRATION IS 'Expiration          Date' ,
  BANKCODE IS 'Bank                Code' ,
  DEBTTYPE IS 'Debt                Type                Code' ,
  STATE IS 'State               Code' ,
  AREACODE IS 'Telephone           Area Code' ,
  EXCHANGE IS 'Telephone           Exchange' ,
  GENDER IS 'Gender              Code' ,
  MARITAL IS 'Marital             Status' ,
  AGEFROM IS 'Age                 Range               From' ,
  AGETHRU IS 'Age                 Range               Thru' ,
  "PROGRAM" IS 'Eligible            Program' ) ;

LABEL ON COLUMN TRUTHDTA/MTRXDETL
( HEADERID TEXT IS 'Header Unique ID' ,
  DETAILID TEXT IS 'Detail Unique ID' ,
  ENABLED TEXT IS 'Enabled (Y/N)' ,
  EFFECTIVE TEXT IS 'Effective Date' ,
  EXPIRATION TEXT IS 'Expiration Date' ,
  BANKCODE TEXT IS 'Bank Code' ,
  DEBTTYPE TEXT IS 'Debt Type Code' ,
  STATE TEXT IS 'State Code' ,
  AREACODE TEXT IS 'Telephone Area Code' ,
  EXCHANGE TEXT IS 'Telephone Exchange' ,
  GENDER TEXT IS 'Gender Code' ,
  MARITAL TEXT IS 'Marital Status' ,
  AGEFROM TEXT IS 'Age Range From' ,
  AGETHRU TEXT IS 'Age Range Thru' ,
  "PROGRAM" TEXT IS 'Eligible Program' ) ;

ALTER TABLE TRUTHDTA/MTRXDETL
  ADD VERSIONING USE HISTORY TABLE TRUTHDTA/MTRXDETLH ;


CREATE INDEX TRUTHDTA/MTRXDETLL1
ON TRUTHDTA/MTRXDETL ( HEADERID ASC , BANKCODE ASC , DEBTTYPE ASC , STATE ASC ,
  AREACODE ASC , EXCHANGE ASC , GENDER ASC , MARITAL ASC , AGEFROM ASC ,
  AGETHRU ASC )
  ;

LABEL ON INDEX TRUTHDTA/MTRXDETLL1
  IS 'Truth Matrix Detail (HeaderID)' ;


CREATE INDEX TRUTHDTA/MTRXHEADL1
  ON TRUTHDTA/MTRXHEAD ( CONDNAME ASC )
  ;

LABEL ON INDEX TRUTHDTA/MTRXHEADL1
  IS 'Truth Matrix Header (CondName)' ;

